### ISSUE TITLE
put example should be good

### ISSUE THREAD

**Issue by misogihagi** [laddge/tanuky#1]
Put the samples in the root directory, and store  them 

./example
├── src # srcdir
│   ├── css
│   │   └── style.css
│   ├── images
│   │   └── dog.jpeg
│   ├── js
│   │   └── main.js
│   ├── pages
│   │   └── example.md
│   └── index.html
├── templates # tpldir
│   └── hoge.html
└── generate.py

**Comment by laddge** [comment]
I’ve done it, thank you.

**Comment by misogihagi** [comment]
really?
see #2
